#=
Every tracked Julia file under `export/` parses.

WHY THIS EXISTS, AND WHY IT IS A TEST RATHER THAN A SCRIPT.

`Meta.parseall` DOES NOT THROW.  It returns a tree with `Expr(:error, ...)` (or
`Expr(:incomplete, ...)`) nodes embedded in it, so

    Meta.parseall(read(path, String)); println("PARSE OK")

prints "PARSE OK" for a file that cannot be loaded at all.  That check was used during the
`:hermite_spline` removal and it was VACUOUS: it reported OK on a file with an unescaped quote
in a docstring.  The error was caught by something else (the file was `include`d moments
later), but the check that was supposed to catch it asserted nothing -- the exact class of
defect that whole branch existed to remove.  Replacing it with another script would leave
nothing to stop a third recurrence, so it is a test, in the suite, in the `ACE_REQUIRE_GROUPS`
list.

WHAT IT COVERS THAT NOTHING ELSE DOES.  Most of `export/` is loaded by the suite or by CI, and
a syntax error there fails loudly on its own.  These are not:

    export/bench/*.jl          diag_dA_conditioning, fit_tial_order4, gate_bench_libs,
                               profile_tensor_step, test_assert_ranks, verify_bench_models
    export/scripts/*.jl        build_deployment, build_portable, deploy_model
    export/examples/*.jl       etace_lammps_tutorial
    export/ase-ace/src/ase_ace/julia/*.jl  ace_driver
    export/test/*.jl           bytecmp_generator, diag_virial_conditioning, debug_ylm

Fifteen files at the time of writing, run by hand or by a benchmark session and by nothing
that gates a merge.  The `:hermite_spline` removal edited four of them.  A syntax error in any
one would have been found by whoever next ran a benchmark, which may be weeks later and is
never the person who introduced it.

THE FILE SET IS `git ls-files`, NOT A DIRECTORY WALK.  A walk would pick up
`export/test/build/*.jl` -- multi-megabyte GENERATED model files, regenerated by the suite --
and would miss nothing in return.  Using the tracked set also means a new file is covered the
moment it is added, with no list here to keep in step: this file has no list.
=#

using Test

const SYNTAX_REPO = normpath(joinpath(@__DIR__, "..", ".."))

"""
    tracked_export_jl() -> Vector{String}

Every tracked `.jl` file under `export/`, as absolute paths.

`git ls-files` rather than a walk, and a hard error rather than a skip if git cannot answer:
a syntax gate that quietly checks zero files is worse than no gate, because it reports
success.  `test_generator_parity.jl` already requires git for the same kind of reason.
"""
function tracked_export_jl()
    out = IOBuffer()
    ok = success(pipeline(`git -C $SYNTAX_REPO ls-files export`; stdout = out))
    ok || error("""
        `git ls-files export` failed, so the set of files to check cannot be determined.
        This gate refuses to check an empty or guessed set -- that would report success
        while asserting nothing, which is the defect it was written to prevent.""")
    files = [joinpath(SYNTAX_REPO, f) for f in split(String(take!(out)), '\n'; keepempty = false)
             if endswith(f, ".jl")]
    return sort(files)
end

"""
    parse_problems(src, label) -> Vector{String}

The parse errors in `src`, as printable strings; empty means it parses.

Walks the WHOLE tree rather than only `Expr(:toplevel).args`, and looks for `:error` AND
`:incomplete` -- an unterminated string or block produces the latter.  Nothing here relies on
an exception being thrown, because none is.
"""
function parse_problems(src::AbstractString, label::AbstractString = "")
    problems = String[]
    function walk(x)
        if x isa Expr
            if x.head === :error || x.head === :incomplete
                push!(problems, string(label, isempty(label) ? "" : ": ",
                                       x.head, " -- ",
                                       first(string(isempty(x.args) ? x : x.args[1]), 400)))
            end
            foreach(walk, x.args)
        end
        return nothing
    end
    walk(Meta.parseall(src))
    return problems
end

parse_problems_file(path::AbstractString) = parse_problems(read(path, String), relpath(path, SYNTAX_REPO))

@testset "every tracked export/*.jl parses" verbose = true begin

    files = tracked_export_jl()

    # A gate that checks nothing passes.  The floor is deliberately well below the current
    # count (40 at the time of writing -- this file is one of them) so that deleting files
    # does not trip it, and well above zero so that a broken `git ls-files`, a wrong working
    # directory or an over-eager filter does.  It is a FLOOR and not an equality on purpose:
    # an exact count would be stale the moment anyone adds a file, which is the failure this
    # comment's own number had in its first commit.
    @testset "the file set is non-empty and plausible" begin
        @test length(files) >= 25
        @test any(endswith(f, "src/export_ace_model.jl") for f in files)
        @test any(endswith(f, "test/runtests.jl") for f in files)
        # the four this branch edited that nothing else loads -- named, so that if one is
        # ever dropped from the tracked set the omission is visible here
        for f in ("bench/verify_bench_models.jl", "bench/gate_bench_libs.jl",
                  "test/bytecmp_generator.jl", "examples/etace_lammps_tutorial.jl")
            @test any(endswith(p, f) for p in files)
        end
    end

    # NEGATIVE TEST.  A check that cannot fail is what this file replaced, so prove this one
    # can, on the two forms that matter and on the exact shape of the bug that motivated it.
    @testset "the check actually detects a broken file" begin
        # (a) the real bug: an unescaped quote inside a one-line docstring, which is what
        #     slipped through the vacuous `Meta.parseall(...); println("PARSE OK")` check.
        bad_doc = """
        "The `include("x.jl")` targets of one source file."
        f(x) = x
        """
        @test !isempty(parse_problems(bad_doc, "bad_doc"))

        # (b) an outright syntax error
        @test !isempty(parse_problems("function f(\nend\n +", "bad_syntax"))

        # (c) an unterminated block -> :incomplete, which is NOT :error and would be missed
        #     by a scan that only looked for one of them
        @test !isempty(parse_problems("function f()\n  1 +", "incomplete"))

        # (d) and a real file written to disk, so the file-reading path is exercised too and
        #     not only the string path
        mktempdir() do dir
            p = joinpath(dir, "broken.jl")
            write(p, "module M\nf(x = = 1) = x\n")
            @test !isempty(parse_problems(read(p, String), "broken.jl"))
        end

        # ... and that something valid reports clean, so the check is not simply always-fail
        @test isempty(parse_problems("module M\nf(x) = x + 1\nend\n", "good"))
    end

    @testset "all $(length(files)) tracked files" begin
        allproblems = String[]
        for f in files
            probs = parse_problems_file(f)
            append!(allproblems, probs)
            isempty(probs) || @error "parse failure" file = relpath(f, SYNTAX_REPO) probs
        end
        isempty(allproblems) ||
            println("\nPARSE FAILURES:\n  ", join(allproblems, "\n  "), "\n")
        @test allproblems == String[]
    end

    println("  syntax gate: $(length(files)) tracked export/*.jl files parsed")
end
